### ISSUE TITLE
Frame alignment and buttons position

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#13]
Three suggestions for the alignment and buttons position

![image](https://cloud.githubusercontent.com/assets/6502098/5330874/f152ab4a-7e07-11e4-94b2-40d6a44b6fd2.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
The 4 boxes are still not properly aligned.

Also, the CLEAR TRANSACTION and SEND TRANSACTION buttons are not on the bottom left corner

**Comment by pmt-it** [comment]
The box alignment is OK now. Still waiting for the buttons

**Comment by jctopo** [comment]
Buttons set at the bottom center

**Comment by pmt-it** [comment]
Verified
