### ISSUE TITLE
Search customer on Search screen

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#17]
Search by Mobile number works but search on the same customer with first and lastname returns nothing. I have checked dbo.SYSTEM_ErrorLog table and has no error.

![image](https://cloud.githubusercontent.com/assets/6502098/5330891/2cc1a27a-7e09-11e4-9dd9-48f886dd920d.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Not fully fixed. Use this credential to login.

username: steven.poh.london
password: password1

NOTE: Also change the SUBMIT button caption to Search

![image](https://cloud.githubusercontent.com/assets/6502098/5347843/29d30188-7f23-11e4-8c0a-4169ec2c9ef2.png)

**Comment by jctopo** [comment]
It is working, check the pic 
![search](https://cloud.githubusercontent.com/assets/6925815/5349134/4d45cdf4-7eeb-11e4-9a1c-e1b79d1c269d.jpg)

**Comment by pmt-it** [comment]
I thought I have closed this as you have told me to go to EDIT and SAVE the record due to NULL values
